version: '3.9'

services:
  nabshopdjango:
    build:
      context: ./nabshopdjango
    command: ./docker-entrypoint.sh
    ports:
      - 8000:8000
    image: nabshop_backend:1
    restart: on-failure
    volumes:
      - ./nabshopdjango:/app
      # - ./nabshopdjango/media:/vol/web
    environment:
      - SECRET_KEY=django-insecure-qoqt=gb(b7^dquy$ohkpai2r-n79i9k%8qepgr#y6g4-%-bo66
      - STRIPE_SECRET_KEY=sk_test_51MnI9lBwcqwfQakZcJKfr282Uh9fQqo9bjbxy8JYqVO2Xk3o9U69hmkrEUZVavTvzFfvozrvDWuChPJo2GV9Vclc00FzDbL7Ne
      # - DJANGO_SETTINGS_MODULE
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=nabshop
      - DB_PASS=root
      - DB_USER=root
      - ALLOWED_HOSTS=0.0.0.0,localhost
    depends_on:
      - db 

  nabshopvue:
    build:
      context: ./nabshopvue
      # dockerfile: Dockerfile.prod
    depends_on:
      - db
    ports:
      - 8080:8080
    image: nabshop_frontend:1
    restart: on-failure
    volumes:
      - ./nabshopvue:/app

  db:
    image: mysql:8.0
    ports:
      - 33000:3306
    restart: always
    environment:
      - MYSQL_DATABASE=nabshop
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysqldata:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password     

volumes:
  mysqldata: