version: '3.9'

services:
  nabshopdjango:
    build:
      context: ./nabshopdjango
    command: ./docker-entrypoint.sh
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      - SECRET_KEY=django-insecure-qoqt=gb(b7^dquy$ohkpai2r-n79i9k%8qepgr#y6g4-%-bo66
      - STRIPE_SECRET_KEY=sk_test_51MnI9lBwcqwfQakZcJKfr282Uh9fQqo9bjbxy8JYqVO2Xk3o9U69hmkrEUZVavTvzFfvozrvDWuChPJo2GV9Vclc00FzDbL7Ne
      # - DJANGO_SETTINGS_MODULE
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=nabshop
      - DB_PASS=root
      - DB_USER=root
      - ALLOWED_HOSTS=143.110.230.206
    depends_on:
      - db 

  nabshopvue:
    build:
      context: ./nabshopvue
      dockerfile: Dockerfile.prod
    depends_on:
      - db
    ports:
      - 80:80
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - 33000:3306
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=nabshop
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysqldata:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password     

volumes:
  mysqldata: