# Generated by Django 4.1.7 on 2023-03-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_author_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='total_amount',
        ),
    ]
