# Generated by Django 4.1.7 on 2023-03-14 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_category_genre_rename_category_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedition',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
