# Generated by Django 4.1.7 on 2023-03-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_amount_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.EmailField(max_length=20),
        ),
    ]
