# Generated by Django 4.1.7 on 2023-03-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_bookedition_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
    ]
