# Generated by Django 4.1.7 on 2023-03-14 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_book_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedition',
            old_name='quantity',
            new_name='stock',
        ),
    ]
