# Generated by Django 4.1.7 on 2023-03-20 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_orderitem_bookedition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='bookedition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitems', to='store.bookedition'),
        ),
    ]
