# Generated by Django 4.1.7 on 2023-03-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_book_created_at_bookedition_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel an order')]},
        ),
    ]
