# Generated by Django 4.1.7 on 2023-03-18 07:09

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_address_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store/images', validators=[store.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='store/thumbnails'),
        ),
    ]
