# Generated by Django 4.1.7 on 2023-03-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_bookimage_image_alter_bookimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedition',
            name='booktype',
            field=models.CharField(choices=[('Ebook', 'Ebook'), ('Paperback', 'Paperback')], default='Ebook', max_length=10),
        ),
    ]
