# Generated by Django 4.1.7 on 2023-03-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
