FROM node:18.15.0-alpine AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production
FROM nginx:1.23-alpine
# RUN addgroup app && adduser -S -G app app
# RUN adduser -S -G app node
# USER app
# COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/nginx.conf
# COPY default.conf /etc/nginx/conf.d/
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]
